### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by dallenmidd** [dallenmidd/IxPopDyMod#41]
Write vignettes for the winter tick (Myles) and Ogden 2005 (Dave).

**Comment by mylesstokowski** [comment]
@dallenmidd re the winter tick, I looked over the R scripts we have in the winter tick [folder](https://github.com/dallenmidd/IxPopDyMod/tree/master/data-raw/winter_tick). They are:
1. `make_inputs.R`: this is reshaping climate data to use in modeling
1. `parameterize_winter_tick.R`: lots of my experiments playing around with components of the config, to get results similar to those in existing studies. This one's very long (~800 lines!), some of which could hopefully be removed in the vignette
1. `dave_script.R`: this is seeing how tweaks to the initial config alter outputs

Just want to do a sanity check before diving into wrapping this up into a vignette. Do you think it makes sense to include all these components? I think the value of showing this whole process would be to show how you might draw from literature to try to build out something that has some biological accuracy. Also simply having all this in a reproducible format complete with outputs would probably be a nice reference for us to have.

**Comment by dallenmidd** [comment]
That sounds good to me! But if you feel like the `parameterize_winter_tick.R` and showing the process gets really bogged down and hard to distill down, then feel free to remove it completely.

**Comment by dallenmidd** [comment]
Do we need separate branches for these vignettes? Or since they are both pretty much contained to their own directories can we both do it on the main branch?

**Comment by dallenmidd** [comment]
@mylesstokowski Makes sense! I will start my own branch.

**Comment by dallenmidd** [comment]
oh I didn't mean to close, I guess the way I linked it to my PR it closed it. I have finished the ogden vignette. I didn't do it as a true vignette but just a readme in the odgen2005 directory. I think that is enough, but if you think it woudl help to have a real vignette happy to do that.

At this point I think we are pretty close to done with the changes we were thinking about. Right? Maybe now I will switch back to the manuscript and finish up the updated draft of that. What do you think?

**Comment by mylesstokowski** [comment]
@dallenmidd just took a look over the Ogden readme - looks great! I don't feel particularly strongly either way re vignette vs readme, so happy to stick with it as is. 

It's helpful to see how you went about composing this document. I think similar would be good for the winter tick - specifically starting with a parameterized model, rather than trying to explain the process of creating it. When I first started looking into updating the winter tick documentation, I realized the process required a lot of experimentation/educated guesswork, plus it'd be a significant amount of work just to get that code to run reproducibly. Anyway, I haven't made much progress on the winter tick, but this will help me.

Regarding next steps, shifting back to the manuscript makes sense to me. There are a few other things that come to mind, some of these are from looking through `TODO`s in the code. Might be low priority/not worth it, but I figure it's at least worth considering before we re-submit to CRAN:
- A few functions have out-of-date function documentation that should be updated (shouldn't take long)
- We're currently erroring out if a vector of variable mortality values is provided (in a duration-based transition). Here's the relevant [code](https://github.com/dallenmidd/IxPopDyMod/blob/5ad76a7d36d13e299d371f2c3dac693d977caee8/R/core_functions.R#L309-L321). Even if we don't fully implement this behavior, it might be worth cleaning up the description of what's going on in this case and updating the error message.
- More validation on outputs from transition functions could be helpful. For example, `run()` would probably break if a transition function returned `NA` or `NULL` or `inf` or `"some_string"`, but it might not be clear why. 
  - Trickier yet is if functions return numeric vectors that are "the wrong" length. I _think_ that our expectation is transition functions should return either a vector of length `1`, or a vector of length `max_duration`, but I don't think we validate this. For example, if there's a transition function that uses 3 host species, that function should do some sort of aggregation so it doesn't return, e.g. a vector of length 3 (which would cause an error downstream).
  - Trying to think through all the cases like this makes my brain hurt! But clearing up what we expect transition functions to return could make the package more robust, easier to describe, and prevent very confusing errors/behavior. Documenting these expectations could be the first step, followed by enforcing them in code. The implementation of these checks _might_ be as simple as adding some `stopifnot()` statements to the end of `get_transition_value()` to ensure the returned value is valid.

**Comment by dallenmidd** [comment]
@mylesstokowski  Oh thanks for keeping track of these. I am happy to defer to you on how much you think any of these is worth it. Do you want to make an issue for each one? Of these I think that I could probably tackle the documentation. I can do that along with updating the manuscript.

**Comment by mylesstokowski** [comment]
Sounds good to me. I'll write up those tasks soon and see how far I can get/whether they seem worthwhile. I believe that most of the out-of-date docs are marked with a `TODO`.

**Comment by dallenmidd** [comment]
Hey @mylesstokowski I just checked out your winter tick vignette. It looks great. Just a couple quick suggestions:

- In the "Modifying moose density" section could you calculate the growth rate for each moose density and add that to this section.
- In the "Modifying climate" could you re-order the levels so they are ordered by temperature not alphabetically. So it goes cold, baseline, warm.
That is it! Other than that looks great.

**Comment by mylesstokowski** [comment]
@dallenmidd this comment had slipped through. Just implemented fixes to your comments in commits https://github.com/dallenmidd/IxPopDyMod/pull/53/commits/dace01e9d57c489be643b0a4a75d21713a1f37f2 and https://github.com/dallenmidd/IxPopDyMod/pull/53/commits/253e9cd90045fd6185372cd10da14a206f0d203e

**Comment by dallenmidd** [comment]
Hi @mylesstokowski I just made some little changes to the winter tick vignette in a new branch (`winter_small_changes`). I changed the name and output so it would should up on the `winter_tick` [page](https://github.com/dallenmidd/IxPopDyMod/tree/winter_small_changes/data-raw/winter_tick). And then you were missing some brackets so it didn't output the growth rates. When I made that change the growth rates don't look good. I know that we have had problems with `growth_rate` before. I thought we had fixed it but maybe there is no way to write a function that will work all the time. Would you mind taking a quick look at it. I will too, but it might be we just have to drop the function.

**Comment by dallenmidd** [comment]
@mylesstokowski OHH sorry spoke too soon. I did fix `growth_rate` looks great now. Will you do a quick review of my changes and then we can merge my new branch and close this comment.

**Comment by dallenmidd** [comment]
@mylesstokowski Hi Myles will you check my new version with `annual_growth_rate` and there is one TODO I see. It is about filling in citations. Since you did the model I assume you know these citations (or can dig them up) better than I can.

https://github.com/dallenmidd/IxPopDyMod/blob/a5a774e031336d3fbac8c6ea735ff33ed15c6b5d/data-raw/winter_tick/README.Rmd#L138

**Comment by dallenmidd** [comment]
> @mylesstokowski Hi Myles will you check my new version with `annual_growth_rate` and there is one TODO I see. It is about filling in citations. Since you did the model I assume you know these citations (or can dig them up) better than I can.
> 
> https://github.com/dallenmidd/IxPopDyMod/blob/a5a774e031336d3fbac8c6ea735ff33ed15c6b5d/data-raw/winter_tick/README.Rmd#L138

Hey @mylesstokowski thanks for all your help these past couple of days! I think that all we have left for the winter tick vignette is this one TODO you left to put citations in. If you have them easily accessible then could you drop them in? Or if it is a huge hassle I could track them down. Then I think we can close this issue.

**Comment by mylesstokowski** [comment]
@dallenmidd agreed we can close this now?
