### ISSUE TITLE
Code for parameter/input comparison

### ISSUE THREAD

**Issue by dallenmidd** [dallenmidd/IxPopDyMod#8]
It would be great to have code which allowed the user to specify two or more parameter values or two+ host communities and then see how that resulted in different model outputs. I think the summary statistic would be something like the lambda (multiplicative growth rate of population). Here is my rough code for lambda based on `out_N_df`:

```
out_N_df %>% 
  group_by(day) %>% 
  summarise(tot = sum(pop)) %>% 
  mutate(lambda = tot/lag(tot)) %>% 
  filter(is.finite(lambda), lambda >0) %>%
  summarise(lambda = exp(mean(log(lambda)))) %>%
  as.numeric()
```

The `exp(mean(log(lambda)))` thing is to get the geometric mean, which is more appropriate in this setting.

**Comment by mylesstokowski** [comment]
> It would be great to have code which allowed the user to specify two or more parameter values or two+ host communities and then see how that resulted in different model outputs. I think the summary statistic would be something like the lambda (multiplicative growth rate of population). Here is my rough code for lambda based on `out_N_df`:
> 
> ```
> out_N_df %>% 
>   group_by(day) %>% 
>   summarise(tot = sum(pop)) %>% 
>   mutate(lambda = tot/lag(tot)) %>% 
>   filter(is.finite(lambda), lambda >0) %>%
>   summarise(lambda = exp(mean(log(lambda)))) %>%
>   as.numeric()
> ```
> 
> The `exp(mean(log(lambda)))` thing is to get the geometric mean, which is more appropriate in this setting.

@dallenmidd I'm thinking again about this. The function run_all_configs() outputs a dataframe like out_N_df but for multiple configs, and we could use this for comparing different model outputs. What exactly do we want to compare between model runs? A couple ideas are:
- adapt the two graphing functions so that they work for output from multiple runs - maybe a grid of output graphs? This would start to get tricky to visualize with a lot of model runs...
- calculate the summary statistic (quoted) for each of the model runs, and return a named list/vector with these numbers for each run

**Comment by dallenmidd** [comment]
Yeah these are two good ideas! I think that the user might want a range of different things to compare (fraction of ticks infected, does the population persist or die out, population size over time,...). We might just need to trust that the user can pull these things out of the `out_N_df` object and do it for each one from a different cfg. But it might be good, as you say, to give one or two automatic ones. I think the two you suggest sound good.

**Comment by mylesstokowski** [comment]
Ok great, I added a super brief function growth_rate() for calculating the growth rate of a single model output. After our meeting I was thinking about your examples, and it's probably simplest for a user to just use lapply() with this growth_rate() function or one of the graphing functions, in order to compare model outputs.

**Comment by mylesstokowski** [comment]
@dallenmidd, closing this because I believe everything in this issue is handled
